
spring:
  ## 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/pingyiquan?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456

  redis:
    host: localhost
    port: 16379
  elasticsearch:
    rest:
      uris: ["http://localhost:19200"]
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: http://localhost:19300 # es的连接地址及端口号
      cluster-name: docker-cluster # es集群的名称




