
spring:
  ## 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pingyiquan?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root

  ## jpa配置
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



  redis:
    host: localhost
    port: 6379

swagger:
  open: true
